# This is a simple profiler based on gcov data. If works as follows:
#   - Run gcov on the gcda files that are generated by instrumented programs, to get annotated source
#   - Extract the data specifying how many times each line of source code has been references
#   - Remove data originating from GNAT's automatically generated files
#   - Summarize the result in a text array using semicolons as a separator

cd ../obj
gcov *.gcda

cd ../tools
echo "File:Line#:Calls" > profile.csv
grep -no "^[[:space:]]*[0-9]\+" ../obj/*.gcov | grep -v -e "../obj/a-" -e "../obj/s-" -e "../obj/b__" >> profile.csv
